---
- hosts: localhost
  vars:
  tasks:
    - name: add psutil
      pip:
        name: '{{ item }}'
      with_items:
        - psutil

    - name: update gnome dconf settings
      dconf:
        key: "{{item.key}}"
        value: "{{item.value}}"
      loop:
        - {key: '/org/gnome/desktop/input-sources/xkb-options', value: "['caps:ctrl_modifier']"}
        - {key: '/org/gnome/desktop/interface/clock-show-date', value: 'true'}
        - {key: '/org/gnome/desktop/interface/cursor-blink', value: 'false'}
        - {key: '/org/gnome/desktop/interface/gtk-theme', value: "'Adwaita-light'"}
        - {key: '/org/gnome/desktop/privacy/old-files-age', value: 'uint32 7'}
        - {key: '/org/gnome/desktop/privacy/remove-old-trash-files', value: 'true'}
        - {key: '/org/gnome/desktop/privacy/report-technical-problems', value: 'false'}
        - {key: '/org/gnome/desktop/search-providers/disable-external', value: 'true'}
        - {key: '/org/gnome/desktop/wm/preferences/audible-bell', value: 'false'}
        - {key: '/org/gnome/desktop/wm/preferences/focus-mode', value: "'sloppy'"}
        - {key: '/org/gnome/settings-daemon/plugins/color/night-light-enabled', value: 'true'}
        - {key: '/org/gnome/settings-daemon/plugins/xsettings/antialiasing', value: "'rgba'"}
        - {key: '/org/gnome/shell/disable-user-extensions', value: 'false'}
        - {key: '/org/gnome/software/allow-updates', value: 'false'}
        - {key: '/org/gnome/software/download-updates', value: 'false'}
        - {key: '/org/gnome/terminal/legacy/default-show-menubar', value: 'false'}

    - name: dnf remove gnome bloat
      dnf:
        name:
          - cheese
          - evolution
          - evolution-ews
          - evolution-help
          - gfbgraph
          - gnome-boxes
          - gnome-calendar
          - gnome-contacts
          - gnome-dictionary
          - gnome-documents
          - gnome-getting-started-docs
          - gnome-initial-setup
          - gnome-maps
          - gnome-online-miners
          - gnome-photos
          - gnome-user-docs
          - gnome-user-share
          - gnome-video-effects
          - gnome-weather
          - totem
          - tracker-miners
          - yelp
        state: absent
      become: true

    - name: ensure core gnome packages are installed
      dnf:
        name:
          - eog
          - evince
          - evolution-data-server
          - flatpak
          - gdm
          - gnome-keyring
          - gnome-menus
          - gnome-screenshot
          - gnome-shell
          - gnome-terminal
          - gnome-tweaks
          - nautilus
          - redhat-menus
        state: present
      become: true

    - name: mask unwanted gnome services
      systemd:
        name: "{{item}}"
        user: yes
        masked: yes
        state: stopped
      loop:
        - evolution-addressbook-factory.service
        - evolution-calendar-factory.service
        - evolution-source-registry.service
        - gvfs-goa-volume-monitor.service
        - tracker-store.service

    - name: remove tracker databases
      file:
        name: ~/.cache/tracker
        state: absent